<?php

namespace BasicBundle\Repository;

/**
 * llibreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class llibreRepository extends \Doctrine\ORM\EntityRepository
{
}
